# Generated by Django 3.1.2 on 2020-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazva', models.CharField(max_length=100, verbose_name='Назва товару')),
                ('opus', models.CharField(max_length=500, verbose_name='Опис товару')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Імейл'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
    ]
